### ISSUE TITLE
kOS integration

### ISSUE THREAD

**Issue by zer0Kerbal** [JPLRepo/TarsierSpaceTechnology#59] opened 2018-06-19 02:23 UTC
Would be wonderful if a kOS processor could use one of the drives as another volume. 

TYIA

**Comment by JPLRepo** [comment] 2018-07-16 02:03
All pull request gratefully accepted.

**Comment by zer0Kerbal** [comment] 2018-07-25 17:45
I've been thinking on how to do such - but my code-fu is severely lacking and what exists is heavily laden with rust. The last compiler I used professionally was Turbo-Pascal. 

Still, extended the functionality of TST"s to allow them to be used for kOS storage volumes... I will continue to ponder and see if I can at least pseudo-code the idea.

**Comment by JPLRepo** [comment] 2018-12-29 04:33
One would presume kOS storage volumes is just a simple case of adding the necessary module to the parts using Module Manager.
No actual coding required. Just a simple text file.

**Comment by luxorpt** [comment] 2019-01-12 20:37
In the last KSP version (1.6.1), there are the problems:
option does not work,
Graphical control window does not open

**Comment by JPLRepo** [comment] 2019-01-12 21:54
That would be because this mod has not been updated for KSP 1.6.x

**Comment by JPLRepo** [comment] 2019-01-12 21:54
Closing this because not a bug.

**Closed as completed by JPLRepo** 2019-01-12 21:54 UTC
